runners:
  - name: "cirun-gcp-amd64"
    cloud: "gcp"
    machine_image: "sealos-dev:cirun-action-podman"  # YOUR-PROJECT-NAME:MACHINE-IMAGE-NAME
    instance_type:
      - "e2-highmem-2"
      - "e2-custom-2-8192"
    labels:
      - "cirun-gcp-amd64"
    region:
      - "asia-east1-a"
      - "asia-east1-b"
      - "asia-east1-c"
      - "us-central1-a"
      - "us-central1-b"
      - "us-central1-c"
      - "us-central1-f"
      - "northamerica-northeast1-a"
      - "northamerica-northeast1-b"
      - "northamerica-northeast1-c"
